# GitHub Nodejs CI
name: pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['10.x']

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          npm install lerna --global
          npm install
          cd timber/ && npm install && cd -
          cd contracts/ && npm install && cd -
        env:
          CI: true
